src/SnackBar/Areas/Admin/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using NLog;
using SnackBar.BLL.Interfaces;
using SnackBar.Controllers;
using SnackBar.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SnackBar.Areas.Admin.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        private Logger _logger = LogManager.GetLogger("AdminEmail");

        public HomeController(IServiceFactory factory) : base(factory)
        {
        }

        // GET: /Admin/Home/Index
        public ActionResult Index()
        {
            var debitors = Factory.GetAdminService().GetAllDebitors();
            var model = Mapper.Map<IEnumerable<UserViewModel>>(debitors);

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> SendAsync()
        {
            _logger.Info($"{User.Identity.Name} start sending Emails...");
            var users = Factory.GetAdminService().GetAllDebitors();
            var debitors = Mapper.Map<IEnumerable<UserViewModel>>(users);
            if (debitors != null)
            {
                try
                {
                    foreach (var user in debitors)
                    {
                        var message = new IdentityMessage()
                        {
                            Subject = "From SnackBar",
                            Body = $"Your Balance is {user.Balance}, please pay!",
                            Destination = user.Email
                        };
                        var client = new SnackBar.EmailService();
                        await client.SendAsync(message).ConfigureAwait(false);
                    }
                }
                catch
                {
                    _logger.Warn("Email not sends");
                    TempData["ErrorEmailSends"] = Resx.Resource.ErrorEmailsNotSent;
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
            }

            _logger.Info($"{User.Identity.Name} send all emails.");
            return RedirectToAction("Index", "Home", new { area = "Admin" });
        }
    }
}

src/SnackBar/Controllers/HomeController.cs
using AutoMapper;
using NLog;
using SnackBar.BLL.Interfaces;
using SnackBar.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SnackBar.Controllers
{
    public class HomeController : BaseController
    {
        private Logger _logger = LogManager.GetLogger("Users");

        public HomeController(IServiceFactory factory) : base(factory)
        {
        }

        [HttpGet]
        public ViewResult Index()
        {
            var products = Factory.GetProductService().GetAllProducts(p => p.Count > 0);
            var model = new ProductListViewModel()
            {
                Pin = HttpContext.Request.Cookies["PIN"]?.Value,
                Products = Mapper.Map<List<ProductViewModel>>(products),
            };

            if (!string.IsNullOrEmpty(model.Pin))
            {
                var userService = Factory.GetUserService();
                model.UserInfo = userService.GetIndexPageInfo(model.Pin);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult TagList(long id = 0)
        {
            var tags = Factory.GetTagService().GetAllTags();
            ViewBag.SelectedTag = id;

            return PartialView("_tagList", tags);
        }

        [HttpGet]
        public ActionResult Category(long? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return this.HttpNotFound();
            }

            var products = Factory.GetTagService().GetProductsByTagId(id.Value);

            if (products == null)
            {
                return this.HttpNotFound();
            }

            var model = new ProductListViewModel()
            {
                Pin = HttpContext.Request.Cookies["PIN"]?.Value,
                Products = Mapper.Map<List<ProductViewModel>>(products),
            };

            if (!string.IsNullOrEmpty(model.Pin))
            {
                var userService = Factory.GetUserService();
                model.UserInfo = userService.GetIndexPageInfo(model.Pin);
            }

            this.TempData["SelectedTag"] = id;
            return View("Index", model);
        }

        [HttpPost]
        public async Task<ActionResult> CreatePin(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                this.TempData["ErrorEmailMessage"] = Resx.Resource.ErrorEmailEmpty;
                return this.RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            _logger.Info($"Start Looking user with Email - \"{email}\"...");
            var address = new MailAddress(email);
            string emailDomen = ConfigurationManager.AppSettings["EmailDomen"];
            if (!emailDomen.Equals(address.Host.ToLower()))
            {
                _logger.Info("Incorrect Email");
                TempData["ErrorEmailMessage"] = string.Format(Resx.Resource.ErrorEmailDomen, ConfigurationManager.AppSettings["CompanyName"]);
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            var userService = this.Factory.GetUserService();

            var user = await userService.RegisterUser(email);

            if (user == null)
            {
                this._logger.Warn($"Error with creating User with email - \"{email}\"");
                TempData["ErrorEmailMessage"] = Resx.Resource.ErrorCreatingUser;
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            _logger.Info($"Success");
            TempData["SuccessMessage"] = Resx.Resource.SuccessMessage;
            return RedirectToAction("Index");
        }

        public ActionResult ChangeCulture(string lang)
        {
            string returnUrl = Request.UrlReferrer.AbsolutePath;
            List<string> cultures = new List<string>() { "en", "ru" };
            if (!cultures.Contains(lang))
            {
                lang = "en";
            }

            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
            {
                cookie.Value = lang;
            }
            else
            {
                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }

            Response.Cookies.Add(cookie);
            return Redirect(returnUrl);
        }
    }
}

src/SnackBar/Controllers/OrderController.cs
using AutoMapper;
using SnackBar.BLL.Interfaces;
using SnackBar.DAL.Models;
using SnackBar.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SnackBar.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController(IServiceFactory factory) : base(factory)
        {
        }

        [HttpGet]
        public ActionResult AddOrder(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Index", "Home", new { area = string.Empty });
            }

            var product = Factory.GetProductService().GetProductById((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }

            var model = new ProductListViewModel()
            {
                Pin = HttpContext.Request.Cookies["PIN"]?.Value,
                Products = new List<ProductViewModel>()
                {
                    Mapper.Map<ProductViewModel>(product),
                }
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddOrder(OrderViewModel model)
        {
            var orderService = Factory.GetOrderService();
            var order = Mapper.Map<Order>(model);
            order = orderService.AddNewOrder(order);
            if (order == null)
            {
                return HttpNotFound();
            }

            var cookie = new HttpCookie("PIN")
            {
                Value = order.Pin,
                Expires = DateTime.Now.AddMonths(1),
            };

            Response.SetCookie(cookie);

            //Send message to trigger
            HttpClient client = new HttpClient();
            var uri = new Uri("https://maker.ifttt.com/trigger/snackbar_buy_product/with/key/bH0X-dChSor4CXMIstTPk_");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var message = new OrderForMakerIFTTTViewModel()
            {
                Company = ConfigurationManager.AppSettings["CompanyName"],
                Date = order.Date.ToString("G"),
                Email = order.User.Email,
                Price = string.Format("{0} BYN", order.Price),
                ProductName = order.Product.Name
            };

            HttpResponseMessage response = await client.PostAsJsonAsync(uri, message);
            //End sending message

            return RedirectToAction("Index", "Home", new { area = string.Empty });
        }
    }
}

src/SnackBar/Controllers/UserController.cs
using AutoMapper;
using NLog;
using SnackBar.BLL.Interfaces;
using SnackBar.ViewModels;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace SnackBar.Controllers
{
    public class UserController : BaseController
    {
        private Logger _logger = LogManager.GetLogger("Users");

        public UserController(IServiceFactory factory) : base(factory)
        {
        }

        [HttpGet]
        public ActionResult Balance(string pin)
        {
            if (!string.IsNullOrEmpty(pin))
            {
                var userService = Factory.GetUserService();
                var returnResult = userService.GetIndexPageInfo(pin);
                var cookie = new HttpCookie("PIN")
                {
                    Value = pin,
                    Expires = DateTime.Now.AddMonths(1),
                };

                Response.SetCookie(cookie);

                return PartialView(returnResult);
            }

            return RedirectToAction("Index", "Home", new { area = string.Empty });
        }

        [HttpPost]
        public ActionResult Login(string Pin)
        {
            if (string.IsNullOrEmpty(Pin))
            {
                TempData["ErrorPinMessage"] = Resx.Resource.ErrorPinEmpty;
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            if (Pin.Length != 4)
            {
                TempData["ErrorPinMessage"] = Resx.Resource.ErrorPinLenght;
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            var user = Factory.GetUserService().GetUserEmailByPin(Pin);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User not found";
                _logger.Info("Incorrect Email");
                TempData["ErrorPinMessageRed"] = Resx.Resource.User404;
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            var cookie = new HttpCookie("PIN")
            {
                Value = Pin,
                Expires = DateTime.Now.AddDays(14),
            };

            Response.SetCookie(cookie);

            return RedirectToAction("Index", "Home", new { area = string.Empty });
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            if (Request.Cookies["PIN"] != null)
            {
                var c = new HttpCookie("PIN");
                c.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(c);
                Session.Abandon();
            }

            return RedirectToAction("Index", "Home", new { area = string.Empty });
        }

        [HttpGet]
        public ActionResult GetOrders()
        {
            var pin = HttpContext.Request.Cookies["PIN"]?.Value;
            if (string.IsNullOrEmpty(pin))
            {
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            var orders = Factory.GetOrderService().GetLastUserOrders(pin);
            var model = Mapper.Map<IEnumerable<OrderListViewModel>>(orders);

            return this.PartialView(model);
        }
    }
}

src/SnackBar/Areas/Admin/Views/Home/Create.cshtml
@using SnackBar.Resx
@{
    ViewBag.Title = Resource.Create;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Resource.CreateNewProduct</h2>
<div class="container">
    @using (Html.BeginForm("Create", "Home", FormMethod.Post))
    {
        <div class="form-group">
            <label for="name">@Resource.ProductName:</label>
            <input type="text" class="form-control" id="name" name="Name">
        </div>
        <div class="form-group">
            <label for="cnt">@Resource.Quantity:</label>
            <input type="text" class="form-control" id="cnt" name="Count">
        </div>
        <div class="form-group">
            <label for="price">@Resource.PricePerOne:</label>
            <input type="text" class="form-control" id="price" name="Price">
        </div>
        <div class="form-group">
            <label for="brc">@Resource.Barcode:</label>
            <input type="text" class="form-control" id="brc" name="Barcode">
        </div>
        <input type="submit" class="btn btn-primary" value="Create" />
    }
</div>

src/SnackBar/Areas/Admin/Views/Home/Index.cshtml
@using SnackBar.Resx
@model IEnumerable<SnackBar.ViewModels.UserViewModel>
@{
    ViewBag.Title = Resource.AdminPage;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Resource.AdminPage</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@Resource.ProductsInBar</h3>
        <a class="btn btn-primary" href="@Url.Action("EditProducts", "Product", new { area = "Admin" })">@Resource.EditProducts</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("Create", "Product", new { area = "Admin" })">@Resource.CreateNewProduct</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("Tags", "Product", new { area = "Admin" })">@Resource.TagList</a><br /><br />
    </div>
    <div class="col-md-4">
        <h3>@Resource.Users</h3>
        <a class="btn btn-primary" href="@Url.Action("AddPayment", "User", new { area = "Admin" })">@Resource.AddPayment</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("GetLastPayments", "User", new { area = "Admin" })">@Resource.LastPayments</a><br /><br />
        @using (Html.BeginForm("GetUserPayments", "User", FormMethod.Get))
            {
            <p>@Resource.EnterUserEmail</p>
            <input type="text" name="email" /><br />
            <input type="submit" style="margin-top:5px" class="btn btn-primary" value="@Resource.UsersPayments" />
        }<br /><br />
        <a class="btn btn-warning" href="@Url.Action("Register", "Account", new { area = "Admin" })">@Resource.RegisterAdmin</a><br /><br />
    </div>
    <div class="col-md-4">
        <h3>@Resource.Orders</h3>
        <a class="btn btn-primary" href="@Url.Action("GetTodayOrders", "Order", new { area = "Admin" })">@Resource.TodayOrders</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("GetMonthOrders", "Order", new { area = "Admin" })">@Resource.ThisMonthOrders</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("GetLastMOrders", "Order", new { area = "Admin" })">@Resource.LastMonthOrders</a><br /><br />
        <a class="btn btn-primary" href="@Url.Action("GetAllOrders", "Order", new { area = "Admin" })">@Resource.AllOrders</a><br /><br />
        @using (Html.BeginForm("GetUserOrders", "Order", FormMethod.Get))
        {
            if (TempData["ErrorEmailInput"] != null)
            {
                <div class="alert alert-warning alert-dismissable fade in">
                    <strong>Warning!</strong> @TempData["ErrorEmailInput"].ToString()
                </div>
            }
            <p>@Resource.EnterUserPinOrEmail</p>
            <input type="text" name="input" /><br />
            <input type="submit" style="margin-top:5px" class="btn btn-primary" value="@Resource.UsersOrders" />
        }<br /><br />
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <h3>@Resource.Debitors</h3>
        <p />
        @{ decimal sum = 0M; }
        <table class="table">
            <thead>
                <tr>
                    <th>@Resource.UsersEmail</th>
                    <th>@Resource.Balance</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    if (user.Balance > -10)
                    {
                        <tr class="warning">
                            <td>@user.Email</td>
                            <td>@user.Balance BYN</td>
                            <td><a class="btn btn-primary btn-sm" href="@Url.Action("AddPaymentByEmail","User",new { area = "Admin", email = user.Email })">@Resource.Pay</a></td>
                        </tr>
                    }
                    else
                    {
                        <tr class="danger">
                            <td>@user.Email</td>
                            <td>@user.Balance BYN</td>
                            <td><a class="btn btn-primary btn-sm" href="@Url.Action("AddPaymentByEmail","User",new { area = "Admin", email = user.Email })">@Resource.Pay</a></td>
                        </tr>
                    }
                    sum += user.Balance;
                }
            </tbody>
        </table>
        @if (TempData["ErrorEmailSends"] != null)
        {
            <div class="alert alert-warning alert-dismissable fade in">
                <strong>Warning!</strong> @TempData["ErrorEmailSends"].ToString()
            </div>
        }
        else
        {
            @Html.ActionLink(Resource.SendEmails.ToString(), "SendAsync", "Home", new { area = "Admin" }, null)<br /><br /><br /><br />
        }
        <p>@Resource.TotalDebit</p>
        <h3>@sum  BYN</h3>
    </div>
</div>